from django.db import models

# Create your models here.
class User(models.Model):
    Name = models.CharField(max_length=30)
    Email = models.CharField(max_length=30)
    Phone = models.CharField(max_length=30)
    college = models.CharField(max_length=30)
    teachlive = models.CharField(max_length=2000)
    Study = models.CharField(max_length=30)
    Labroom = models.CharField(max_length=100)
    Workroom = models.CharField(max_length=100)
    Achievement = models.CharField(max_length=3000)
    yanjiufield = models.CharField(max_length=3000)
    keyanfield = models.CharField(max_length=3000)
    patent = models.CharField(max_length=3000)
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100)
    Username = models.CharField(max_length=30)
    Password = models.CharField(max_length=30)
    Leixing = models.CharField(max_length=30)
class order(models.Model):
    orderusername = models.CharField(max_length=30)
    daoshi = models.CharField(max_length=30)
    xingming = models.CharField(max_length=30)
    week = models.CharField(max_length=200)
    day = models.CharField(max_length=200)
    time = models.CharField(max_length=200)
    where = models.CharField(max_length=100)
    telephone = models.CharField(max_length=100)
    shenghe = models.CharField(max_length=30)
    count = models.CharField(max_length=30)
class Work(models.Model):
    username = models.CharField(max_length=30)
    time = models.CharField(max_length=2000)
    worktravel = models.CharField(max_length=2000)
class Book(models.Model):
    username = models.CharField(max_length=30)
    shu = models.CharField(max_length=2000)
    author = models.CharField(max_length=2000)
    bookdate = models.CharField(max_length=2000)
    publisher = models.CharField(max_length=2000)
class dat(models.Model):
    username = models.CharField(max_length=100)
    numberweek = models.CharField(max_length=100)
    weeknumber = models.CharField(max_length=100)
    weekonefirst = models.CharField(max_length=100)
    weektwofirst = models.CharField(max_length=100)
    weekthreefirst = models.CharField(max_length=100)
    weekfourfirst = models.CharField(max_length=100)
    weekfivefirst = models.CharField(max_length=100)
    weekonesecond = models.CharField(max_length=100)
    weektwosecond = models.CharField(max_length=100)
    weekthreesecond = models.CharField(max_length=100)
    weekfoursecond = models.CharField(max_length=100)
    weekfivesecond = models.CharField(max_length=100)
    weekonethird = models.CharField(max_length=100)
    weektwothird = models.CharField(max_length=100)
    weekthreethird = models.CharField(max_length=100)
    weekfourthird = models.CharField(max_length=100)
    weekfivethird = models.CharField(max_length=100)
    weekonefifth = models.CharField(max_length=100)
    weektwofifth = models.CharField(max_length=100)
    weekthreefifth = models.CharField(max_length=100)
    weekfourfifth = models.CharField(max_length=100)
    weekfivefifth = models.CharField(max_length=100)
    weekonefourth = models.CharField(max_length=100)
    weektwofourth = models.CharField(max_length=100)
    weekthreefourth = models.CharField(max_length=100)
    weekfourfourth = models.CharField(max_length=100)
    weekfivefourth = models.CharField(max_length=100)
    
    

